title: Intengine
default_lang: en
author:
  name: 'Frank Jaeger'
  email: sylwester.pilarz93@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: Intengine
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
