title: Hola
author:
  name: Devlom
  email: 'info@devlom.com'
metadata:
    description: 'Hola is a modern and stylish vCard website template. Designed to be a resume, vCard, portfolio template, it’s the perfect template for creative designers, developers, freelancers, photographer or any creative profession.'
taxonomies: [category,tag,author]
